language: python

python:
  - 2.7
  - 3.2
  - 3.4
  - 3.5
  - pypy
  - nightly


install:
  - 'pip install coverage'
  - 'python setup.py install'

script: 'coverage run test.py'

after_success:
  - 'coverage report -m'
  - 'pip install codacy-coverage'
  - 'python-codacy-coverage -r coverage.xml'